[target.riscv32imac-unknown-none-elf]
#runner = "espflash flash --monitor --chip esp32c6 --log-format defmt --partition-table=partitions.csv"
runner = "probe-rs run --chip=esp32c6 --probe 303a:1001 --rtt-scan-memory --preverify --always-print-stacktrace --catch-hardfault --idf-partition-table=partitions.csv"

[env]
ESP_LOG="info"
DEFMT_LOG="info"
SSID=""
PASSWORD=""

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
